version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: ktfuf7tnen6idaqrh3gojc/demo
    steps:
      - run: echo "Hi I'm on Runners!"